### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by saikatharryc** [activitree/s3up-meta#1]
i'm trying like this:
```
 Meteor.call(
            "authorize_upload",
            document.getElementById("avatar").files, //this is the file object direct from the input box
            (err, done) => {
                if (err) {
                    console.log(err);
                    alert(err);
                }
                console.log(done);
            }
        );
```
it gives me file_name cannot be empty. any help?

**Comment by paulincai** [comment]
@saikatharryc do you still need this? I am here in case you need help. Just tag me if you need help, please.

**Comment by saikatharryc** [comment]
@paulincai  would be great if you could clarify this query now also, although i have used some other package already. but it can help others if someone wants to use it. or may be someday when i will use.

**Comment by paulincai** [comment]
Hi @saikatharryc , I updated the documentation and also updated the libraries. This should be ok now.
