### ISSUE TITLE
Use environment variables instead of settings.json

### ISSUE THREAD

**Issue by ivonigC** [activitree/s3up-meta#3]
Hi @paulincai,

Seems like a great package, trying to implement. Is there a way to use Environment variables rather than settings.json for passing the keys ?

Thanks

**Comment by paulincai** [comment]
authorize_upload is a server side function. You call this via a method on your server. To that method you can provide authentication data from any source you prefer so the answer is yes, there is a way yo do it, the same way you would use env vars in any other context. You are already on the server.

Ex: 

```javascript
// server side
import { authorizer as Authorizer } from '@activitree/s3up-meta/server' // or your own package. This package is presently private.

const services = {
    key: process.env.AWS_ACCESS_KEY_ID,
    secret: process.env.AWS_SECRET_ACCESS_KEY,
    bucket: process.env.AWS_BUCKET,
    region: process.env.AWS_S3_REGION
  }

const authorizer = new Authorizer(services)

 authorize_upload: function (ops, metadata) {
    check(ops, Object)
    Match.test(metadata, Match.OneOf(Object, undefined, null))
    this.unblock()
    return authorizer.authorize_upload(metadata, ops)
  }

```

**Comment by ivonigC** [comment]
Yep, didn't think that through here :)

Thanks a lot.
